### PR TITLE
Adds missing comma, this breaks CI

### PR DESCRIPTION
**Pull request by ashr81**
This breaks our flow `typechecker` on our application and CI after upgradation

### CODE REVIEW

**Comment by QuintinWillison** [comment]
@codemerx I've added you as a reviewer as it looks like your change, 21747fdd, added a message without comma. Is there any reason it should not have a comma on the end?

**Comment by codemerx** [comment]
> @codemerx I've added you as a reviewer as it looks like your change, [21747fd](https://github.com/ably/ably-common/commit/21747fdd63a5bb2b405fb34c37723ba1a0d99bff), added a message without comma. Is there any reason it should not have a comma on the end?

It seems like an error on my side.

**Comment by QuintinWillison** [comment]
Hello @ashr81 - is your CI encountering this error as a result of building `ably-js`? If so then I'll need to bump the submodule reference there.

**Comment by ashr81** [comment]
Hi @QuintinWillison , yes our CI is breaking because of this error on running flow type checks.

**Comment by SimonWoolf** [comment]
Suggestion: add to the readme a recommendation that anyone editing add a pre-push hook (`.git/hooks/pre-push`) that does something like
```sh
grep -v "\/\*" ./protocol/errors.json | jq type;
```
as a quick sanity-check prevent malformed json being committed

**Comment by QuintinWillison** [comment]
I wouldn't go as far as configuring a Git hook as that's arguably something that's up to the personal taste of the contributor.

It would seem helpful, however, to have something that can be run to validate the formation of the documents in this repository. Developers can then be encouraged to run that locally before pushing (use a Git hook if that's the way _they_ like to work) as it will also be run in a CI environment as we do elsewhere.

I've created issue #52 for this.

**Comment by ashr81** [comment]
hi @QuintinWillison , can you please bump the submodule version with updated code.

**Comment by QuintinWillison** [comment]
It's [in develop](https://github.com/ably/ably-js/commit/340e5ce31dc9d7434a06ae4e1eec32bdacc9c6c5) in ably-js, we just need to do the release. Is that what you need, @ashr81?

**Comment by ashr81** [comment]
Hi @QuintinWillison , no problem we locked `ably` package at version: `1.1.22` in our `package.json`. Take your time. once your changes are done we will update the package.

**Comment by QuintinWillison** [comment]
Hello @ashr81 - thanks for your patience on this one. I should have updated you when we did it but then just remembered now - we've [released 1.1.24](https://github.com/ably/ably-js/releases/tag/1.1.24) with this PR included. Hopefully that'll resolve things for you when it's convenient to you to change your `package.json` file again. 😄

**Pull request merged**
