### PR TITLE
Expected value proposal

### PR DESCRIPTION
**Pull request by paddybyers**
Any comments/updates before we merge?

Perhaps `expectedHexValue` for the binary case?

I still think `object` and `array` would have been fine :)

### CODE REVIEW

**Comment by mattheworiordan** [comment]
> Perhaps expectedHexValue for the binary case?

I wouldn't be against that

> I still think object and array would have been fine :)

I disagree.  I like the fact that we are being explicit that `object` and `array` are as defined in the JSON spec for `object` and `array` as opposed to generic `object` and `array` implementations.

**Comment by tcard** [comment]
I actually went ahead and cherry-picked your commit onto https://github.com/ably/ably-common/pull/16.

Kind of messy that we have three PRs now overlapping and/or building on top of each other. Should I close this, merge #16 (which incorporates this) and then review/merge #18 ?

**Comment by tcard** [comment]
Actually, I've closed #16 and now I think we should merge this one and then #18. Both look good to me and I'll go ahead an update https://github.com/ably/ably-ios/pull/459 to #18.

**Comment by mattheworiordan** [comment]
I agree.  We should prioritise this as it is blocking our PHP dev as he does not want to reference a branch.  @paddybyers you ok to do what @tcard suggested?

**Comment by paddybyers** [comment]
> @paddybyers you ok to do what @tcard suggested?

I merged them both without squashing.

**Pull request merged**
