### PR TITLE
Move network locations into ably-common

### PR DESCRIPTION
**Pull request by mattheworiordan**
We are working with an external agency on one of our demos.

They need the location data of our datacenters and all PoPs. See conversation at https://ably-real-time.slack.com/archives/C03LRNNSG/p1671113935662879 for context. 

As this data currently resides in a private repo for the website, this PR moves that data into ably-common. 

A matching PR for the website exists that ensures data from ably-common can be easily synced to the website.  See https://github.com/ably/website/pull/5245

### CODE REVIEW

**Review by QuintinWillison — COMMENTED** [review]
I saw this pull request come by in passing, given review wasn't requested from me... If I could make one small request then that would be to remove the `ably-` prefix from the new folder name please. The context is already clear, given the org name is `ably` and the repository name is `ably-common`. Also, none of the existing root folders in this repository have or need to have `ably` in their names. Thanks.

**Comment by mattheworiordan** [comment]
> I saw this pull request come by in passing, given review wasn't requested from me... If I could make one small request then that would be to remove the `ably-` prefix from the new folder name please. The context is already clear, given the org name is `ably` and the repository name is `ably-common`. Also, none of the existing root folders in this repository have or need to have `ably` in their names. Thanks.

Yes, makes sense, I did start with `network` first, but for some reason added the prefix which I can't recall!

**Review by QuintinWillison — APPROVED** [review]
https://github.com/ably/ably-common/pull/176/commits/3e0076a536851f2fff06c9a57ac0a67a8b778615 fixes zealous, unnecessary CI check. 😉

**Comment by dpiatek** [comment]
@QuintinWillison I don't have merge access here, but happy with the changes from the website's perspective

**Comment by kennethkalmer** [comment]
> [3e0076a](https://github.com/ably/ably-common/commit/3e0076a536851f2fff06c9a57ac0a67a8b778615) fixes zealous, unnecessary CI check. 😉

Thanks @QuintinWillison, I was gonna ask what on earth that obscure linting issue was

**Comment by mattheworiordan** [comment]
Thanks @QuintinWillison for allowing bare URLs :)

**Pull request merged**
